import { formatMoney } from './state.js';
import { getChallengeLabel } from './challenges.js';

export function buildWeekMarkdown(state, resolution = state.lastResolution) {
  if (!resolution) return '# IndulgeCare Clinic\n\nNo week resolution yet.';

  const staffGain = resolution.staffGains?.reduce((s, i) => s + i.gain, 0) || 0;
  const patientGain = resolution.patientGains?.reduce((s, i) => s + i.gain, 0) || 0;
  const stageLines = (resolution.stageChanges || [])
    .map((c) => `- **${c.name}**: stage ${c.oldStage + 1} → ${c.newStage + 1} (+${c.gain.toFixed(1)} lb)`)
    .join('\n');

  const recentLog = state.log?.find((l) => l.type === 'resolution' && l.week === resolution.week);
  const logSnippet = recentLog
    ? recentLog.text.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 500)
    : '';

  return `# IndulgeCare Clinic — Week ${resolution.week}

**${state.clinicName}** · ${state.doctorName}  
Reputation ${state.reputation} · Money ${formatMoney(state.money)}  
Challenge: ${getChallengeLabel(resolution.challengeWeek || state.challengeWeek)}

## Summary

- Staff gain: **${staffGain.toFixed(1)} lb**
- Patient gain: **${patientGain.toFixed(1)} lb**
- Stage changes: **${resolution.stageChanges?.length || 0}**
- Revenue: ${formatMoney(resolution.clinicRevenue || 0)} · Bills: ${formatMoney(resolution.bills || 0)}

## Stage changes

${stageLines || '_None this week._'}

## Resolution excerpt

${logSnippet || '_No archive excerpt._'}

---
_Generated by IndulgeCare Clinic_`;
}

export async function copyWeekSummary(state) {
  const md = buildWeekMarkdown(state);
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(md);
    return { ok: true, message: 'Week summary copied to clipboard.' };
  }
  return { ok: false, message: 'Clipboard unavailable in this browser.' };
}
